### PR TITLE
fix dropdown menu text color in black theme

### PR DESCRIPTION
**Pull request by ra100**
add: !important;
add: .gitignore lines related to Atom editor project files

### CODE REVIEW

**Comment by Alex-D** [comment]
Can you clean your PR? There is a useless merge commit.

Editor-specific ignores are not to be placed in the gitignore. You need to ignore them locally.

And the endline is useless in JavaScript so it's not important. Each contributor add or remove this line at each PR :/

**Comment by ra100** [comment]
sorry, will fix my commits, now I see I have there garbage and add ignore newlines at commit. Can you discard this pull request?

**Comment by Alex-D** [comment]
You can just rebase your branch and force push them to update this PR :)

**Comment by ra100** [comment]
It took a bit of time, byt I learned something :) Thanks
Now there is only that one tiny change/fix.

**Comment by Alex-D** [comment]
Great! :)
Thanks

**Pull request merged**
