### PR TITLE
Allow users to set the width of an image in the modal

### PR DESCRIPTION
**Pull request by AbdelElrafa**
We should allow them to edit the width of an image easily in the modal.

### CODE REVIEW

**Comment by AbdelElrafa** [comment]
@Alex-D I have added this change to my code and it really is a nice feature. I saw before in many comments you rejected the idea but I think that this solution is clean and doesn't hurt to have it. Most people aren't smart enough to adjust the size of their images locally before pasting.

**Comment by Alex-D** [comment]
OK. But this should be an option set to false by default.

**Comment by AbdelElrafa** [comment]
@Alex-D Done. Should I add height too? I don't think it would be a good idea to since that can cause distortion.

**Comment by Alex-D** [comment]
It looks good to me :)

**Pull request merged**
