### PR TITLE
Mathml plugin

### PR DESCRIPTION
**Pull request by loclamor**
A basic MathJax / MathML integration to Trumbowyg.

It allow formulas insertion, and more formulas edition.

Working demo could be found here : http://utest.favier.it/mathtest/

### CODE REVIEW

**Comment by Alex-D** [comment]
Seems legit :)

Could you add some doc to the docs folder in another PR?

**Comment by loclamor** [comment]
Thanks for merging ;)

Wich kind of docs would you want ?

Le 19 déc. 2017 6:45 PM, "Alexandre Demode" <notifications@github.com> a
écrit :

**Comment by Alex-D** [comment]
Like other plugins :)

Doc: https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-emoji
+ demo: https://alex-d.github.io/Trumbowyg/demos/#plugins-emoji

**Comment by loclamor** [comment]
obviously -_-'

**Pull request merged**
