### PR TITLE
Upload events added

### PR DESCRIPTION
**Pull request by hiendv**
An alternative to #306

### CODE REVIEW

**Comment by hiendv** [comment]
As you can see `data` is optional and could be omitted on `upload.error`
An example (ES6)
```js
$(node).trumbowyg()
.on('upload.success', (trumbowyg, data, url) => {
    console.log(trumbowyg, data, url)
})
.on('upload.error', (trumbowyg, data) => {
    console.log(trumbowyg, data)
})
```

**Comment by Alex-D** [comment]
Can you follow the core event name "normalization"?
See here: http://alex-d.github.io/Trumbowyg/documentation.html#events

Something like `tbwuploadsuccess` and `tbwuploaderror` maybe

**Comment by Alex-D** [comment]
Thanks! And sorry to be exigent ^^'

**Comment by hiendv** [comment]
@Alex-D I changed the names and it's my fault for not following the convention. It's okay. Anyway, what are your opinions on another naming convention for events? Let's say `namespace.plugins.event`. E.g. `tbw.upload.success`

**Comment by Alex-D** [comment]
I've tested them, but jQuery has his own event namespace management which is strange and not vanilla compatible (or I was wrong).

**Comment by hiendv** [comment]
@Alex-D I didn't know the difference. jQuery even supports [`event.namespace`](https://api.jquery.com/event.namespace/) or am I missing something?

**Comment by Alex-D** [comment]
jQuery yep, but it's not a JavaScript standard. But I need to take a look over that again.

**Comment by hiendv** [comment]
@Alex-D Totally understand. We will talk about it later, in another discussion ;).
Targeting to 2.2.x or 3.x.x maybe :smile:

**Pull request merged**
