### PR TITLE
[ Wording ] Small updates

### PR DESCRIPTION
**Pull request by edwinveldhuizen**
They're just small, but the wording matches better with MS Word and are less "technical"

### CODE REVIEW

**Comment by Alex-D** [comment]
I'm not OK to change that officially. If you want to change that in your project, you can by using your own language file.

Sorry :/

**Comment by edwinveldhuizen** [comment]
Ok, but currently the wording is a bit inconsistent, so what is the process for changing existing wording?
Or can one only add new languages and then no-one can change it anymore? ever?

**Comment by edwinveldhuizen** [comment]
'Strong', 'Emphasis', 'Unordered list' and 'Ordered list' are not really terms that are used

**Comment by Alex-D** [comment]
> Or can one only add new languages and then no-one can change it anymore? ever?

I did not understand your point.

If you want change the wording in your project, you can, you just need to create your own language file, then use it.

https://alex-d.github.io/Trumbowyg/documentation/#add-localization

**Comment by Alex-D** [comment]
Also, bold and strong are not the same. Since Trumbowyg try to be semantic, it support both.

Strong is the `strong` tag, bold is the `b` one. Which is not the same at all.

**Comment by edwinveldhuizen** [comment]
I get your point from a technical perspective, but if we have a look at the following languages, they all call them the same as well.
The reason that we call them the same, is because for the end-user they are the same thing. Technically not the same at all, but for a less-technical end-user ( who are the actual users of a wysiwyg editor ) they are the same.

*bg*
```
    bold: 'Удебелен',
    italic: 'Наклонен',

    strong: 'Удебелен',
    em: 'Наклонен',
```

*by*
```
    bold: 'Паўтлусты',
    italic: 'Курсіў',

    strong: 'Паўтлусты',
    em: 'Курсіў',
```

*cs*
```
    bold: 'Tučné',
    italic: 'Kurzíva',

    strong: 'Tučné',
```

*el*
```
    bold: 'Έντονα',
    italic: 'Πλάγια',

    strong: 'Έντονα',
    em: 'Πλάγια',
```

*es*
```
    bold: 'Negrita',
    italic: 'Cursiva',

    strong: 'Negrita',
```

*fa*
```
    italic: 'مورب',
    em: 'مورب',
```

And many more

**Comment by Alex-D** [comment]
OK. So make me a new PR but without capitalize.

**Comment by edwinveldhuizen** [comment]
`Align Left',  'Align Right' and 'Insert Image' are currently also capitalised.
That's why we were making it consistent

**Comment by edwinveldhuizen** [comment]
Shall I change those to non-capitalised as well, or keep all capitalised?

**Comment by Alex-D** [comment]
Change to non-capitalised :)

Thanks for your time!

**Pull request closed without merging**
