### PR TITLE
[Plugin] Improve cleanpaste by only analyzing pasted content

### PR DESCRIPTION
**Pull request by forelabs**
I do not like that the cursor is resetted everytime you paste something,
so I have improved the cleanpaste plugin that it will:

- only analyze new pasted content
- add content right behind current cursor
- set cursor right after pasted content

### CODE REVIEW

**Comment by forelabs** [comment]
Btw  I use the insert part in a few plugins i wrote / modified.
Maybe it makes sense to extract it to a Trumbowyg core function?

**Comment by Alex-D** [comment]
> Maybe it makes sense to extract it to a Trumbowyg core function?

Depends if it's usefull for the core. If not, no. If yes, we need to check that.

**Comment by forelabs** [comment]
I think it is useful, there were already several requests / bug reports because of that: https://github.com/Alex-D/Trumbowyg/issues?utf8=✓&q=is%3Aissue+cursor+position

It's the wanted behaviour that when you insert something via plugin, it should be inserted where you at + you should stay with your cursor where you at. Getting the cursor set to start of editor is not what the user expects.

I will use single quotes and test it with browserstack on the mentioned browsers + on mobile devices too

**Comment by Alex-D** [comment]
If it's light, I'm OK to add it to core, if core can benefit from it, it could be a good point! :)

**Comment by Alex-D** [comment]
What's up there? :)

**Comment by forelabs** [comment]
Sry had a lot of different stuff to do, I also have to test this one again, last time I used it I had some troubles with word content, but this plugin is exactly for that case so it should work. Sry to let you wait, will have a look into it the next days

**Comment by dfreerksen** [comment]
What is the status of this?

This resolves the issue I am having where pasting content at the bottom of the content area moves the cursor and pastes it at the top instead.

**Comment by Alex-D** [comment]
Need to be rebased anyway :/

**Comment by Alex-D** [comment]
Maybe this one can be fixed too #805 ?

**Comment by SadegOussama** [comment]
Hello,

I still have the same problem as described above(when I paste a text the cursor goes up, and when it is a link, the link is stuck at the top with the cursor), what can I do to solve it ? I imported cleanpaste well.

Thank you.

**Comment by danreg** [comment]
any updates on this?

**Comment by malandles** [comment]
Confirms that this PR works well on Chrome Version 75.0.3770.100

**Pull request closed without merging**
