### PR TITLE
Added some needed basic security/filtering to the upload plugin.

### PR DESCRIPTION
**Pull request by mrwigster**
It's not incredible - but better than spreading the completely insecure file at current.

### CODE REVIEW

**Comment by Alex-D** [comment]
I do not provide a backend script, it's juste a script for test purposes.

**Comment by Alex-D** [comment]
See: https://github.com/mrwigster/Trumbowyg/blob/ce44ac8dd230e80e19503e63408a4a3ad2bb71a9/plugins/upload/trumbowyg.upload.php#L11

**Comment by mrwigster** [comment]
That's fair enough - I just thought it may have been useful to share a script that was at least a tiny bit securer rather than the current.

**Comment by Alex-D** [comment]
That's just for the dev phase, not for production, if the code is too long, it's hard to be efficient on the Trumbowyg side.

**Pull request closed without merging**
