### PR TITLE
Little bug fix when using the *tbwchange* event

### PR DESCRIPTION
**Pull request by netbull**

### CODE REVIEW

**Comment by Alex-D** [comment]
You PR is dirty :(
Your fix is not a correct fix.
What's the problem that you want solve?

**Comment by netbull** [comment]
When using it like this:

`$('#editor')
    .trumbowyg()
    .on('tbwchange', function(){ console.log("click"); });`

the event is triggered two times in a row

**Comment by Alex-D** [comment]
Use a throttle :)

**Comment by netbull** [comment]
to use what ? O_O

**Comment by Alex-D** [comment]
If you want to avoid the bounce effect, use a debouce or throttle method.

**Comment by netbull** [comment]
the debounce method doesn't work.. the event is still called two times

**Comment by Alex-D** [comment]
Yep, but if you don't want to do 2 times an action, you just have to debounce it.

```
$('#your-editor').trumbowyg();
$('#your-editor').on('tbwchange', _.debounce(function () {
    console.log('CHANGE!');
}));
```

**Comment by netbull** [comment]
Yep, this is exactly what I did :) even I test if I initialize the editor twice by mistake or something, but no.. it's initialized only once, but with, or without the debounce the event is fired twice.

The editor is initialized in a Backbone View, but now I'm experimenting to switch from Backbone to ReactJS, so will see there how it will handle.

**Pull request closed without merging**
