### PR TITLE
plugin resizimg: updated plugin to fit jquery-resizable 0.35

### LINKED ISSUE #1191: risizimg: jquery-resizable update to 0.35
Hi all, 

I have seen the update on the plugin jquery-resizable and I will try soon to create a PR to update the resizimg plugin in the way to use `resizableSafe` instead of `resizable` and remove the `resizable-resolveconflict.js` file. 

In this moment the plugin give some problem with the new version of `jquery-resizable` and I'm testing the code to verify if it work well with new code modifications.

### PR DESCRIPTION
**Pull request by PiemP**
Fixes #1191

updated the plugin to use the `resizableSafe` function instead of the `resizable` to avoid conflict with jquery UI.

removed file resizable-resolveconflicts.js.

updated the documentation: specified the jquery-resizable version's used.

### CODE REVIEW

**Comment by agriffard** [comment]
@Alex-D Would you have some time to review this PR?

**Comment by agriffard** [comment]
@Alex-D Can you please have a look at this PR? 
Thank you.

**Comment by agriffard** [comment]
@Alex-D Can you please find some time to review this PR? 
It would help us if it was merged and a new version was available.
Thank you in advance.

**Comment by momentum-tunis** [comment]
No news on this PR?

**Comment by Alex-D** [comment]
Thank you :)

**Comment by momentum-tunis** [comment]
Thank you very much @Alex-D  👍 
@agriffard now we are waiting for orchard core to integrate the next release of Trumbowyg

**Comment by ned-kelly** [comment]
Hi @Alex-D - any chance we can see this one added into a release?

**Pull request merged**
