### PR TITLE
Add code highlight plugin by prismjs.

### PR DESCRIPTION
**Pull request by kirillurgant**
Add code highlight plugin by prismjs.
It depend of global Prism and prism.css. I did not include it in the repository, what would you advise in this case?

### CODE REVIEW

**Comment by Globulopolis** [comment]
> I did not include it in the repository, what would you advise in this case?

Provide an option for this.

And it's better to do not use an ID for inputs to avoid possible conflicts if user page allready have tag with this ID value.

**Comment by kirillurgant** [comment]
> Provide an option for this.
I can write instructions for this plugin.

**Comment by kirillurgant** [comment]
I wrote the documentation. What do you think about this?

**Comment by Alex-D** [comment]
Thanks! LGTM :)

**Pull request merged**
