### PR TITLE
Added Dutch localization file

### PR DESCRIPTION
**Pull request by dhiemstra**
Thanks :-)

### CODE REVIEW

**Comment by Alex-D** [comment]
Hi! Thanks for your contribution!

Can you add this translation that come with V2 soon ?

https://github.com/Alex-D/Trumbowyg/blob/master/src/trumbowyg.js#L36

Thanks again! :)

**Comment by dhiemstra** [comment]
Added the missing string "removeFormat".

**Comment by Alex-D** [comment]
You could be proud of your contribution =D

**Comment by dhiemstra** [comment]
You can be proud of this plugin! Thanks for your work. ;-)

**Pull request merged**
