### PR TITLE
trumbowyg.js: Remove ES6 code

### PR DESCRIPTION
**Pull request by jorrit**
Was inserted in v2.10.0 / #727.

### CODE REVIEW

**Comment by Alex-D** [comment]
Good catch! Thanks :)

**Comment by jorrit** [comment]
You're welcome. Is it possible to create a new release with this change?

**Comment by pandalion** [comment]
@Alex-D Hi Alex, I have installed Trumbowyg 2.10.0 through npm, but I am still seeing the old code with `const` in it. Please could you let me know if you will be publishing this fix to npm or perhaps I have missed it. Thanks.

**Comment by Alex-D** [comment]
I've totally forget about that. I will do that ASAP.

**Comment by mallen** [comment]
@Alex-D Any chance of a release with this fix included. Thanks

**Comment by Alex-D** [comment]
Arf, yep, sorry I need to take the time to do that ^^'

**Pull request merged**
