### PR TITLE
fix: paragraph issue on first text element

### LINKED ISSUE #516: First paragraph isn't wrapped around with P tags
After updating to the latest version 2.5.1. When I first write a paragraph and press enter, the first paragraph isn't wrapped around with p tags, whether on the second ENTER, it does. It wasn't like that in the 2.4.2 version. In the older version, when I pressed ENTER after finishing the first paragraph, it was inside P tags.

Using latest Chrome browser Version 56.0.2924.87 on Windows 7.

### PR DESCRIPTION
**Pull request by alvesjtiago**
Fixes #516

### CODE REVIEW

**Comment by Alex-D** [comment]
Thanks! :)

**Comment by alvesjtiago** [comment]
Thank you for the great project 😊

**Comment by paul-crashley** [comment]
Is this change in v2.10.0? I've just run into this issue myself using the latest tagged version.

**Comment by Alex-D** [comment]
Yep, this commit is in v2.10.0

**Pull request merged**
