### PR TITLE
Start fullscreen option

### PR DESCRIPTION
**Pull request by adalenv**

### CODE REVIEW

**Comment by Alex-D** [comment]
I was thinking about an API to allow to exit fullscreen too :/

**Comment by adalenv** [comment]
there is the button for that lol

**Comment by Alex-D** [comment]
Yep but if you are a dev and want to open/close fullscreen the best is an API, not an option on the constructor :)

**Comment by adalenv** [comment]
how will you do it?

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L175

Something like that.

**Comment by adalenv** [comment]
it will not open in fullscreen if you have to asign other options

**Pull request closed without merging**
