### PR TITLE
Update emoji codepoints to JoyPixels v6.6.0

### PR DESCRIPTION
**Pull request by zanechua**

### CODE REVIEW

**Comment by zanechua** [comment]
Would be savvy if we could get this labeled as `hacktoberfest-accepted`

**Comment by zanechua** [comment]
@Grafikart

Are you maintaining this repo instead of Alex now?

Details here: https://github.com/Alex-D/Trumbowyg/pull/827

Basically this updates the codepoints for emoji's so we'll get access to newer emojis in the emoji plugin.

No one else seems to be maintaining the codepoints and since I was the one who made the initial change, it's kinda my baby at this point.

**Review by Grafikart — APPROVED** [review]

**Review by Alex-D — APPROVED** [review]

**Comment by Alex-D** [comment]
Thank you :)

As a side note: everyone is free to review the code, so if @Grafikart wanted to review it, he can :) And I understand that a PR without any message can be hard to review.

Also, I've read the hacktoberfest things, it seems that merging works the same as the label. I do not want to create labels dedicated to hacktoberfest since it makes no sens other months ^^

**Comment by zanechua** [comment]
Oh that's neat. :)

Sure, no qualms about that. Thanks @Alex-D and @Grafikart

**Pull request merged**
