### PR TITLE
Fix IE11 Error Could not complete the operation.

### PR DESCRIPTION
**Pull request by sgolomedov**
Fix IE11 Error 'Could not complete the operation due to error 800a025e', that sometimes appears on start.
https://stackoverflow.com/questions/16160996/could-not-complete-the-operation-due-to-error-800a025e
Fix Issue https://github.com/Alex-D/Trumbowyg/issues/196

### CODE REVIEW

**Comment by Alex-D** [comment]
Why not just catch any error with a try-catch block? It will be more safe I think.

**Comment by M0ns1gn0r** [comment]
Unconditional `catch` without analyzing the specific error/exception is considered bad practice.

**Comment by Alex-D** [comment]
Yep but it's small (less chars). Since Trumbowyg should keep everything small as possible, I think try-catch should be OK.

**Comment by sgolomedov** [comment]
@Alex-D Short try/catch version added.

**Comment by Alex-D** [comment]
Thanks :)

**Pull request merged**
