### PR TITLE
Update vue.js component link

### PR DESCRIPTION
**Pull request by ankurk91**
Hi, 
Just created a new Vue.js component

**Advantage over previous component**
* Published on [npm](https://www.npmjs.com/package/vue-trumbowyg)
     - `npm install vue-trumbowyg`
* Not supplying css by default, user can add css or sass
    - Dont force users to install `sass-loader`
* `v-model` is reactive (two way sync)
* Can be used without webpack (directly in browser)
* Up to date with Vue.js v2.0
* supports vee-validate validation library
* has examples in same repo

Please review the [repo](https://github.com/ankurk91/vue-trumbowyg) and let me know if i am missing something

### CODE REVIEW

**Comment by Alex-D** [comment]
It's OK for me, not tested but I trust you!
Thanks! :)

**Comment by ankurk91** [comment]
Thanks!
Here is the demo link if you are interested -
https://jsfiddle.net/ankurk91/p7xs2jkk/1/

**Comment by Alex-D** [comment]
Arf. It didn't works :/

Did you test it on Chrome?

**Comment by ankurk91** [comment]
Yes, I did. It (middle) is still working for me.
Chrome 60 , Mac OS Sierra.

I will create a webpack bin and post here soon.
Dont worry.

**Comment by Alex-D** [comment]
If you write some chars, you will see that it add new chars at start and wrap all in `<p>` each times.

**Comment by ankurk91** [comment]
Agree, but I did not changed anything .
I am using default api provided by editor.
May be it is default behavior.
I will confirm soon.

**Comment by ankurk91** [comment]
Fixed 
https://jsfiddle.net/ankurk91/p7xs2jkk/5/
Released a new version 1.0.3

**Comment by Alex-D** [comment]
Good job! :=)

**Pull request merged**
