### PR TITLE
Table plugin, with SVG icon

### PR DESCRIPTION
**Pull request by absalomedia**
Very basic table plugin for Trumbowyg - stable

Inital commit for b7, now patched for b8 plugin code

### CODE REVIEW

**Comment by Alex-D** [comment]
Basic but seems to be good enough!

I take a look ASAP.

Thanks :)

**Comment by texelate** [comment]
Will this get added to the main branch? Thanks.

**Comment by b1rdex** [comment]
@Alex-D any eta for review?

**Comment by Alex-D** [comment]
I don't have time to review, so I just merged it :)

**Comment by Alex-D** [comment]
I've released your plugin in [v2.2.0](https://github.com/Alex-D/Trumbowyg/tree/v2.2.0)
Thanks for your contribution!

**Comment by texelate** [comment]
Excellent!

**Pull request merged**
