### PR TITLE
Add generic upload file plugin for creating links

### LINKED ISSUE #739: Uploading Files (not images)
This is definitely not a current "bug" or anything of the sort - more of a question. Is it possible to use the uploader to upload files and create links to said files (IE uploading a PDF) ? From what I can tell, the current uploader plugin is limited to images (which makes sense)... 

Any assistance would be great!

### PR DESCRIPTION
**Pull request by jakejohns**
Close #739

This is basically just a slightly modified version of the image upload plugin that can be used to upload a generic file and create a link to it.

### CODE REVIEW

**Comment by jakejohns** [comment]
Any thoughts here?

**Comment by anandiamy** [comment]
not work on latest Firefox

**Comment by jakejohns** [comment]
I havent tested yet, @anandiamy, but is the image upload broken too? do you have any more information, logs, errors, etc?

**Comment by Alex-D** [comment]
Can add this plugin to the plugin documentation section, and create the demo page?

Thank you :)

**Comment by humam-abd** [comment]
Hey @Alex-D,
Checkout this PR #1289

**Pull request closed without merging**
