### PR TITLE
Add a plugin for uploading files(not images)

### LINKED ISSUE #739: Uploading Files (not images)
This is definitely not a current "bug" or anything of the sort - more of a question. Is it possible to use the uploader to upload files and create links to said files (IE uploading a PDF) ? From what I can tell, the current uploader plugin is limited to images (which makes sense)... 

Any assistance would be great!

### LINKED ISSUE #1287: Need an Upload file plugin(Not images)
I've came across a plugin built by @jakejohns in this issue #987 for uploading files like pdfs or docs. But it doesn't seem to be working in firefox browser(v 97.0.1). Can anybody help with this? It seems like `createLink` command is not working or `a` tag is not getting added to `trumbowyg.$box` in the uploadfile plugin [in this repo branch](https://github.com/jakejohns/Trumbowyg/tree/feature/uploadfile/plugins)

### PR DESCRIPTION
**Pull request by humam-abd**
Closes #739 & Closes #1287
Hey @Alex-D,
This is a plugin for uploading files(not images). This is working fine on chrome as well as firefox browsers. Please take your time to review this.

### CODE REVIEW

**Comment by Alex-D** [comment]
Hey,

Same as here: https://github.com/Alex-D/Trumbowyg/pull/987#issuecomment-734004579

Can you add documentation and a demo?

**Review by Alex-D — CHANGES_REQUESTED** [review]
Hey,

Same as here: https://github.com/Alex-D/Trumbowyg/pull/987#issuecomment-734004579

Can you add documentation and a demo?

**Comment by humam-abd** [comment]
**Documentation**

How to use it?

```
<-- Import Trumbowyg plugins... -->
<script src="trumbowyg/dist/plugins/upload/trumbowyg.uploadfile.js"></script>
```
            
Then you can use the new button definition uploadfile

```

$('#my-editor').trumbowyg({
    btns: [
        ['uploadfile']
    ],
    plugins: {
        uploadfile: {
            // Some uploadfile plugin options(same as upload plugin except `imageWidthModalEdit`)
        }
    }
});
```

**Comment by humam-abd** [comment]
> Hey,
> 
> Same as here: [#987 (comment)](https://github.com/Alex-D/Trumbowyg/pull/987#issuecomment-734004579)
> 
> Can you add documentation and a demo?

Hey @Alex-D,
Checkout the demo and documentation i just added. Thanks.

**Comment by Alex-D** [comment]
Thank you, I will create documentation pages myself :)

**Pull request merged**
