### PR TITLE
Events added

### PR DESCRIPTION
**Pull request by hiendv**
`onSuccess` & `onError` added

### CODE REVIEW

**Comment by Alex-D** [comment]
Hi,
this is not an event, that is a callback.

There is already a `success` and `error` functions. I'm OK if you want trigger an event, but not for callback, sorry.

**Comment by hiendv** [comment]
@Alex-D Hi, by saying "Events" I meant the callbacks for the corresponding events.
The problem with the current implementation is: I don't want to override the default behavior of these callbacks, I just want to have "my callbacks" dispatched when the default methods are finished.

**Comment by hiendv** [comment]
So I should make another PR which triggers these events or it's already implemented?

**Comment by Alex-D** [comment]
You can make a PR, that would be awesome :)

**Comment by hiendv** [comment]
@Alex-D Please check my latest PR #309 ;)

**Pull request closed without merging**
