### PR TITLE
new plugin 'resizimg': add image resizing capability

### PR DESCRIPTION
**Pull request by geonanorch**
I understand that image resizing can be a bad thing when huge files are downloaded only to display a small 32x32 picture in the browser. So OK no resizing in Trumbowyg Core.

But clearly (looking at #14, #142, #157, #168, and more recently #671 (and I probably missed a few issues) there is a need for that functionality in some cases. 

I implemented for my own needs a plugin (using another jQuery plugin) which will make all images resizable by dragging their bottom-right corner and though I would give back to the community by contributing --because Trumbowyg is about the best open editor around here :-)

Possible future work:
- relative size instead of absolute size
- resize handle (hopefully pure CSS)

### CODE REVIEW

**Comment by Alex-D** [comment]
I'm not really OK to get `plugins/resizimg/jquery-resizable.min.js` into Trumbowyg repository.
It should be a link to a CDN/official site in docs :)

And for dev purpose, maybe add it to the package.json dev dependencies.

**Comment by Alex-D** [comment]
What's up?

**Comment by geonanorch** [comment]
Hi Alex-D, and thank you for your interest :-)
I understand, it does not make sense to include an external dependency in the code. Here is the situation: 

To support `resizimg` I had to add a `destroy` method to the `resizable` plugin. I submitted a [pull request](https://github.com/RickStrahl/jquery-resizable/pull/27) for that plugin, but haven't heard from @RickStrahl  until now.

Possibly he is still on holiday or busy. I propose to wait another week (and I will ping him). If nothing happens then I would merge the `resizable` code into `resizimg` and update this PR (I made a couple of improvements in the meantime anyway). OK for you ?

**Comment by geonanorch** [comment]
OK, the `jquery-resizable` plugin was updated yesterday so I was able to externalize it.
I just pushed a new version of the `resizimg` plugin reflecting this and including other fixes/improvements.
I tested the live demo using a local HTTP server (the current demo framework does not seem to support external links though, I had to hack a bit), ready for you to review.

**Comment by jung-hunsoo** [comment]
It would be great if I can use this feature in Trumbowyg.

Most of my webapp users are not good at using image editor, but a general end-user. And I'd like to provide as convenient as possible service.

**Comment by Alex-D** [comment]
I just need to take the time to try it, then I will merge that :)

**Comment by dartg** [comment]
Thanks a lot for this! Very useful.

**Comment by afaraha8403** [comment]
Hey @Alex-D  & @geonanorch 

Just wondering about the resize handles.  Anything yet?

Thanks for the great work, I am loving this 👍

**Comment by Alex-D** [comment]
Feel free to add them in a Pull Request, I think you can do that with an img::before (or ::after) + box-shadow hacky CSS way :)

**Comment by geonanorch** [comment]
@afaraha8403 images are replaced elements, more difficult to manage than regular elements. I developed a solution for my needs, but it involves Javascript (+ jquery) and is a bit 'hacky'.
@Alex-D I would be interested to implement a pure CSS solution, can you describe the hack you have in mind? Afaik `before::` & `after::` are not good for replaced elements, but I do not know about that `box-shadow` trick, happy to learn!

**Comment by geonanorch** [comment]
@Alex-D that is the replaced element issue I mentioned earlier, that approach does not work (basic background on [stackoverflow](https://stackoverflow.com/questions/7396469/why-dont-before-and-after-pseudo-elements-work-with-img-elements)). I solved it by adding a wrapper around IMG elements, but on top of being a bit convoluted it is not 100% transparent for contenteditables / your editor. Maybe you can think of something better?

**Comment by Alex-D** [comment]
Arf OK.

So, what about an DOM element which will be manipulated in JS to change his absolute position to be over the image, but with `pointer-event: none`? With that, you do not change the content, only add an editor "meta" DOM element.

**Pull request merged**
