### PR TITLE
Reduce ctrl button lock-in to 50ms

### PR DESCRIPTION
**Pull request by Meekohi**
Related to Issue #566, I'm still finding that some users trying to do `Ctrl+A`, `Delete` are not seeing their change propagate because of the 200ms lock-in after releasing the Ctrl button. Recommend changing this to 50ms to give a better chance of this working.

I'm not sure what the origin of the lock-in is exactly. If someone knows where that came from maybe we can find a solution that works for both use cases. I'm guessing this was just to avoid some corner case where people release the `Ctrl` key a little too early?

### CODE REVIEW

**Comment by Alex-D** [comment]
I think it was before composition and ctrl was splited.

So it's seems legit to reduce that duration.

**Comment by Alex-D** [comment]
Thanks :)

**Comment by Meekohi** [comment]
Sounds good, although if the timeout/lockin doesn't serve a purpose anymore should I just remove it entirely?

**Comment by Alex-D** [comment]
Idk really... we need to test it in different cases.

**Pull request merged**
