### PR TITLE
Fix for cleanpaste

### PR DESCRIPTION
**Pull request by Geniekort**
Solving the bug as described in #881 , by adding a timeout to the execution in of the cleanpaste plugin.

### CODE REVIEW

**Comment by Alex-D** [comment]
What are you trying to fix like that? You are just delaying a push in an array :/

That's the moment when the plugin is registered into Trumbowyg. Are you sure to load `trumbowyg` *then* `trumbowyg.cleanpaste` ?

**Comment by Geniekort** [comment]
You are right, this should fix it

**Comment by Alex-D** [comment]
Did you test it?

**Comment by Geniekort** [comment]
Yes I tested it. It would be nice if we had some specs to run for Trumbowyg. Nice to see that you are actively developing it!

**Comment by Alex-D** [comment]
I hope unit-test/spec for v3 :)

**Pull request merged**
